name: Deploy Workflow

on:
  workflow_call:
    inputs:
      env-vars:
        description: 'JSON string of project specific environment variables'
        required: false
        type: string
        default: '{}'

jobs:
  set-deployment-vars:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.image-name.outputs.image }}
      env-flags: ${{ steps.set-vars.outputs.env-flags }}
      container-name: ${{ steps.set-vars.outputs.container-name }}
      image_src: ${{ steps.set-vars.outputs.full-image-name }}
    steps:
      - name: Compute variables
        id: vars
        env: 
          ENV_JSON: ${{ inputs.env_vars }}
        run: |
          # Compute ENV_FLAGS from env-vars
          ENV_FLAGS=$(echo "$ENV_JSON" | jq -r 'to_entries | map("-e \(.key)=\(.value)") | join(" ")')
          echo "env-flags=$ENV_FLAGS" >> $GITHUB_OUTPUT
          # Compute CONTAINER_NAME and IMAGE_NAME
          REF="${{ github.ref }}"
          TAG_NAME="${REF##*/}"
          REPO_NAME="${{ github.event.repository.name }}"
          CONTAINER_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="${CONTAINER_NAME}:${TAG_NAME}"
          IMAGE_SRC="${{ secrets.DOCKER_REPO }}/${IMAGE_NAME}"

          echo "image-name=${IMAGE_NAME}" >> "$GITHUB_OUTPUT"
          echo "image_src=${IMAGE_SRC}" >> "$GITHUB_OUTPUT"
          echo "container-name=${CONTAINER_NAME}" >> "$GITHUB_OUTPUT"

  build-and-deploy:
    needs: set-deployment-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t "${{ needs.set-deployment-vars.outputs.image_src }}" .
          docker push "${{ needs.set-deployment-vars.outputs.image_src }}"

      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Pulling image"
            docker pull "${{ needs.set-deployment-vars.outputs.image_src }}"

            echo "Checking if container ${{ needs.set-deployment-vars.outputs.container-name }} exists..."
            if [ "$(docker ps -aq -f name=^${{ needs.set-deployment-vars.outputs.container-name }}$)" ]; then
              echo "Stopping and removing existing container..."
              docker stop "${{ needs.set-deployment-vars.outputs.container-name }}"
              docker rm "${{ needs.set-deployment-vars.outputs.container-name }}"
            else
              echo "No existing container found."
            fi

            echo "Running new container..."
            docker run -d \
              --restart unless-stopped \
              -p "${{ secrets.EXPOSED_PORT }}:${{ secrets.INTERNAL_PORT }}" \
              --name "${{ needs.set-deployment-vars.outputs.container-name }}" \
              ${{ needs.set-deployment-vars.outputs.env-flags }}\
              "${{ needs.set-deployment-vars.outputs.image-src }}"

            echo "Deployment complete."
